os:
- linux
- osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11.4
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- swift package resolve
script:
- swift build
- swift test
