os: osx
osx_image: xcode11.4
language: swift
install:
  - brew update
  - brew upgrade git
  - brew install git-lfs
  - git lfs install
  - swift package resolve
script:
  - swift build
  - swift test