jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.4
env:
  global:
  - FRAMEWORK_NAME=AssetLib
before_install:
  - bash -e ./Scripts/before_install.sh
script:
  - bash -e ./Scripts/script.sh