jobs:
    include:
        - os: linux
            dist: bionic
            sudo: required
        - os: osx
            osx_image: xcode11.4
    before_install:
        - ./Scripts/install.sh
    script:
        - ./Scripts/script.sh
