jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.4
env:
  global:
  - FRAMEWORK_NAME=AssetLib
  - SWIFT_VER=5.2
before_install:
  - bash -e ./Scripts/install.sh
script:
  - bash -e ./Scripts/script.sh