meta:
  description: A Swift library and CLI that allows you to convert a Git repository of large files to Git LFS pointers.
  vendor: LebJe
  maintainer: LebJe
files:
  "/usr/bin/LFSPointers":
    file: LFSPointers
    mode: "0755"
  "/etc/bash_completion.d/LFSPointers.bash":
    file: LFSPointers.bash
  "/usr/share/zsh/site-functions/_LFSPointers":
    file: _LFSPointers
