name: Build Container

on: [push]

jobs:
  BuildContainer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.latest
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/lebje/lfs-pointers:latest
            
  BuildTaggedContainer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        id: get-latest-tag
        run: |
          export TAG="$(git describe --abbrev=0 --tags)"
          echo "::set-output name=TAG::$TAG"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/lebje/lfs-pointers:${{ steps.get-latest-tag.outputs.TAG }}