name: Build and Test

on: [push, pull_request]

jobs:
  TestOnMacOS-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  TestOnUbuntu-ARM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v1.1.0
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt update -q
            apt install -yq curl sudo
            curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
            apt install -yq swiftlang
            apt update -yq
            swift test

  TestOnUbuntu-x86_64:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test
  # Uncomment and update as needed when an Apple Silicon VM is available.
  #TestOnMacOS-ARM:
  #runs-on: macos-silicon-latest
  #- uses: actions/checkout@v2
  #- name: Build
  #   run: bash Scripts/install.sh
  # - name: Run tests
  #   run: bash Scripts/script.sh
