name: Generate Documentation

on: push

jobs:
  GenerateDocumentation:
	runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v2
	  - name: Generate Documentation
		uses:  MaxDesiatov/swift-doc@prebuilt-image
		with:
		  inputs: "Sources"
		  module-name: LFSPointersKit
		  output: ./.build/documentation
		  format: html    
	  - name: Change Permissions
		run: sudo chmod o+r -R ./.build/documentation   
	  - name: Deploy to GitHub Pages
		if: success()
		uses: peaceiris/actions-gh-pages@v3
		with:
		  github_token: ${{ secrets.GITHUB_TOKEN }}
		  publish_dir: ./.build/documentation

  # Uncomment and update as needed when an Apple Silicon VM is available.
  #TestOnMacOS-ARM:
	#runs-on: macos-silicon-latest
	#- uses: actions/checkout@v2
	#- name: Build
	#   run: bash Scripts/install.sh
	# - name: Run tests
	#   run: bash Scripts/script.sh

