name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: Scripts/install.sh
    - name: Run tests
      run: Scripts/script.sh