name: Build, Package, and Upload

on:
  - release

jobs:
  PackageOnMacOS-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        run: |
          swift build -c release
          mkdir lfspointers-macos-x86_64
          cp .build/release/LFSPointers lfspointers-macos-x86_64
          tar -czf lfspointers-macos-x86_64.tar.gz lfspointers-macos-x86_64
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lfspointers-macos-x86_64.tar.gz
          asset_name: lfspointers-macos-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

# Swift 5.3 Developer Snapshots aren't available yet.
#
#  PackageOnUbuntu-ARM:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: uraimo/run-on-arch-action@v1.1.0
#        with:
#            architecture: aarch64
#            distribution: ubuntu18.04
#            run: |
#              export DEBIAN_FRONTEND=noninteractive
#              apt update -q
#              apt install -q -y curl sudo
#              curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
#
#              # Get Swift for ARM.
#              apt install -q -y swift-lang
#              apt update -q -y
#              swift build -c release --static-swift-stdlib
#              mkdir lfspointers-linux-aarch64
#              cp .build/release/LFSPointers lfspointers-linux-aarch64
#              tar -czf lfspointers-linux-aarch64.tar.gz lfspointers-linux-aarch64
#      - name: Upload Binaries
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: lfspointers-linux-aarch64.tar.gz
#          asset_name: lfspointers-linux-aarch64.tar.gz
#          tag: ${{ github.ref }}
#          overwrite: true
#          body: ""
#
  PackageOnUbuntu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        run: |
          SWIFT_VER="5.3"
          RELEASE_DOT=$(lsb_release -sr)
          RELEASE_NUM=${RELEASE_DOT//[-._]/}
          wget https://swift.org/builds/swift-${SWIFT_VER}-release/ubuntu${RELEASE_NUM}/swift-${SWIFT_VER}-RELEASE/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
          tar xzf swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
          export PATH="${PWD}/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_NUM}/usr/bin:$PATH"
          swift build -c release --enable-test-discovery -Xswiftc -static-stdlib -Xswiftc -static-executable
          mkdir lfspointers-linux-x86_64
          cp .build/release/LFSPointers lfspointers-linux-x86_64
          tar -czf lfspointers-linux-x86_64.tar.gz lfspointers-linux-x86_64
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lfspointers-linux-x86_64.tar.gz
          asset_name: lfspointers-linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

