name: Build, Package, and Upload

on:
  - release
env:
  APP_NAME: 'LFSPointers'
  MAINTAINER: 'LebJe'
  DESC: 'A command line tool and SPM package that allows you to convert a Git repository directory of large files to Git LFS pointers.'

jobs:
  PackageOnMacOS-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release
          mkdir lLFSPointers-$TAG-macOS-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-macOS-amd64
          tar -czf LFSPointers-$TAG-macOS-amd64.tar.gz LFSPointers-$TAG-macOS-amd64
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

# Swift 5.3 Developer Snapshots aren't available yet.
#
#  PackageOnUbuntu-ARM:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: uraimo/run-on-arch-action@v1.1.0
#        with:
#            architecture: aarch64
#            distribution: ubuntu18.04
#            run: |
#              export DEBIAN_FRONTEND=noninteractive
#              apt update -q
#              apt install -q -y curl sudo
#              curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
#
#              # Get Swift for ARM.
#              apt install -q -y swift-lang
#              apt update -q -y
#              swift build -c release --static-swift-stdlib
#              mkdir lfspointers-linux-aarch64
#              cp .build/release/LFSPointers lfspointers-linux-aarch64
#              tar -czf lfspointers-linux-aarch64.tar.gz lfspointers-linux-aarch64
#      - name: Upload Binaries
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: lfspointers-linux-aarch64.tar.gz
#          asset_name: lfspointers-linux-aarch64.tar.gz
#          tag: ${{ github.ref }}
#          overwrite: true
#          body: ""
#
  PackageOnUbuntu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          # SWIFT_VER="5.3"
          # RELEASE_DOT=$(lsb_release -sr)
          # RELEASE_NUM=${RELEASE_DOT//[-._]/}
          # wget https://swift.org/builds/swift-${SWIFT_VER}-release/ubuntu${RELEASE_NUM}/swift-${SWIFT_VER}-RELEASE/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
          # tar xzf swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
          # export PATH="${PWD}/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_NUM}/usr/bin:$PATH"
          # We have to use a developer snapshot for now since Swift 5.3 still cannot build a static executable.
          wget https://swift.org/builds/swift-5.3-branch/ubuntu1804/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-09-09-a/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-09-09-a-ubuntu18.04.tar.gz
          tar xzf swift-5.3-DEVELOPMENT-SNAPSHOT-2020-09-09-a-ubuntu18.04.tar.gz
          export PATH="${PWD}/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-09-09-a-ubuntu18.04/usr/bin:$PATH"
          swift build -c release --enable-test-discovery -Xswiftc -static-stdlib -Xswiftc -static-executable
          mkdir LFSPonters-$TAG-linux-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-linux-amd64
          tar -czf LFSPointers-$TAG-linux-amd64.tar.gz LFSPointers-$TAG-linux-amd64
      - name: Create deb and rpm structure
        run: |
          mkdir -p .debpkg/usr/bin
          echo mkdir
          mkdir -p .rpmpkg/usr/bin
          echo cp
          cp .build/release/LFSPointers .debpkg/usr/bin/
          echo cp
          cp .build/release/LFSPointers .rpmpkg/usr/bin/
          echo done
      - uses: jiro4989/build-deb-action@v2
        with:
          package: ${{ env.APP_NAME }}
          package_root: .debpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: '${{ env.DESC }}'
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
      - name: Upload Deb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true

